{
 "title": "DocumentFactory Monitoring",
 "tags": [
  "documentfactory",
  "prometheus",
  "monitoring"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ptfdservice_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 100",
     "legendFormat": "{{app}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "process_working_set_bytes / 1024 / 1024",
     "legendFormat": "{{app}}: {{instance}}"
    }
   ]
  },
  { "title": "Workflows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Executions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(ptfd_workflow_counter{instance=\"$instance\"}[$__interval])) by(workflow_type) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(ptfd_workflow_errors{instance=\"$instance\"}[$__interval])) by (workflow_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(ptfd_workflow_latency_sum{instance=\"$instance\"}[$__interval])) by (workflow_type)\n/ \nsum(rate(ptfd_workflow_latency_count{instance=\"$instance\"}[$__interval])) by (workflow_type)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Executions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ptfd_workflow_counter[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ptfd_workflow_errors[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Execution Time (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ptfd_workflow_latency_sum{instance=\"$instance\"}[$__range])) \n/\nsum(increase(ptfd_workflow_latency_count{instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Artifacts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(ptfd_artifact_counter[$__interval])) by (artifact_type, artifact_action)",
     "legendFormat": "Type: {{artifact_type}} | Action: {{artifact_action}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(ptfd_artifact_errors[$__interval])) by (artifact_type, artifact_action)",
     "legendFormat": "Type: {{artifact_type}} | Action: {{artifact_action}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(ptfd_artifact_latency_sum[$__interval])) by (artifact_type, artifact_action)\n/\nsum(rate(ptfd_artifact_latency_count[$__interval])) by (artifact_type, artifact_action)\n",
     "legendFormat": "Type: {{artifact_type}} | Action: {{artifact_action}}"
    }
   ]
  },
  {
   "title": "Total Uploads",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ptfd_artifact_counter{artifact_action=\"upload\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Upload Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ptfd_artifact_errors{artifact_action=\"upload\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Average Execution Time (ms)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ptfd_artifact_latency_sum{artifact_action=\"upload\"}[$__range])) / sum(increase(ptfd_artifact_latency_count{artifact_action=\"upload\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Downloads",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ptfd_artifact_counter{artifact_action=\"download\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Download Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ptfd_artifact_errors{artifact_action=\"download\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Average Execution Time (ms)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ptfd_artifact_latency_sum{artifact_action=\"download\"}[$__range])) / sum(increase(ptfd_artifact_latency_count{artifact_action=\"download\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(ptfd_job_counter[$__interval])) by (job_type, job_processortype)",
     "legendFormat": "Type: {{job_type}} | Processor: {{job_processortype}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(ptfd_job_errors[$__interval])) by (job_type, job_processortype)",
     "legendFormat": "Type: {{job_type}} | Processor: {{job_processortype}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(ptfd_job_latency_sum[$__interval])) by (job_type, job_processortype)\n/\nsum(rate(ptfd_job_latency_count[$__interval])) by (job_type, job_processortype)",
     "legendFormat": "Type: {{job_type}} | Processor: {{job_processortype}}"
    }
   ]
  },
  {
   "title": "Total Executions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ptfd_job_counter[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ptfd_job_errors[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Execution Time (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ptfd_job_latency_sum{instance=\"$instance\"}[$__range])) \n/\nsum(increase(ptfd_job_latency_count{instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Document Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(ptfd_docprocessor_counter[$__interval])) by (processor_type, processor_action)\n",
     "legendFormat": "Action: {{processor_action}} | Type: {{processor_type}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(ptfd_docprocessor_errors[$__interval])) by (processor_type, processor_action)\n",
     "legendFormat": "Action: {{processor_action}} | Type: {{processor_type}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(ptfd_docprocessor_latency_sum[$__interval])) by (processor_type, processor_action)\n/\nsum(rate(ptfd_docprocessor_latency_count[$__interval])) by (processor_type, processor_action)\n",
     "legendFormat": "Action: {{processor_action}} | Type: {{processor_type}}"
    }
   ]
  },
  {
   "title": "Total Executions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ptfd_docprocessor_counter[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(ptfd_docprocessor_errors[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Execution Time (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ptfd_docprocessor_latency_sum{instance=\"$instance\"}[$__range])) \n/\nsum(increase(ptfd_docprocessor_latency_count{instance=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}